(function(){
  const V=['$199','$250','$300','$350','$400','$450','$500','$550','$600','$650','$700','$750','$800','$850','$900','$950','$999','$1,299','$1,599','$1,999','$2,499','$2,999','$3,499','$3,999'];
  let C=1,S=[],T='2\u20134 Weeks',A=false;
  window.openProjectForm=function(){document.getElementById('pfOverlay').classList.add('open');document.body.style.overflow='hidden'};
  window.closeProjectForm=function(){document.getElementById('pfOverlay').classList.remove('open');document.body.style.overflow=''};
  window.pfHandleOverlay=function(e){if(e.target===document.getElementById('pfOverlay'))closeProjectForm()};
  window.pfToggleSvc=function(c){const s=c.dataset.service;c.classList.toggle('pf-selected');if(c.classList.contains('pf-selected')){if(!S.includes(s))S.push(s)}else S=S.filter(x=>x!==s);if(S.length>0)document.getElementById('pfESvc').style.display='none'};
  window.pfUpdateBudget=function(v){document.getElementById('pfBudgetDisplay').textContent=V[v]};
  window.pfSelectTL=function(el){document.querySelectorAll('.pf-tl-opt').forEach(o=>o.classList.remove('pf-selected'));el.classList.add('pf-selected');T=el.dataset.val};
  window.pfToggleTerms=function(){A=!A;const b=document.getElementById('pfCheckbox');if(A){b.classList.add('pf-checked');document.getElementById('pfETerms').style.display='none'}else b.classList.remove('pf-checked')};
  function Sf(id){const el=document.getElementById(id);if(el){el.focus({preventScroll:true});setTimeout(function(){el.scrollIntoView({block:'center',behavior:'smooth'})},100)}}
  function Vd(){let ok=true,fe=null;if(C===1){const n=document.getElementById('pfName').value.trim(),e=document.getElementById('pfEmail').value.trim(),c=document.getElementById('pfCountry').value;if(!n){document.getElementById('pfEName').style.display='block';document.getElementById('pfName').classList.add('pf-error');ok=false;if(!fe)fe='pfName'}else{document.getElementById('pfEName').style.display='none';document.getElementById('pfName').classList.remove('pf-error')};if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(e)){document.getElementById('pfEEmail').style.display='block';document.getElementById('pfEmail').classList.add('pf-error');ok=false;if(!fe)fe='pfEmail'}else{document.getElementById('pfEEmail').style.display='none';document.getElementById('pfEmail').classList.remove('pf-error')};if(!c){document.getElementById('pfECountry').style.display='block';document.getElementById('pfCountry').classList.add('pf-error');ok=false;if(!fe)fe='pfCountry'}else{document.getElementById('pfECountry').style.display='none';document.getElementById('pfCountry').classList.remove('pf-error')}}else if(C===2){if(S.length===0){document.getElementById('pfESvc').style.display='block';ok=false;fe='pfESvc'}else document.getElementById('pfESvc').style.display='none'}else if(C===3){const d=document.getElementById('pfDesc').value.trim();if(d.length<20){document.getElementById('pfEDesc').style.display='block';document.getElementById('pfDesc').classList.add('pf-error');ok=false;fe='pfDesc'}else{document.getElementById('pfEDesc').style.display='none';document.getElementById('pfDesc').classList.remove('pf-error')}}else if(C===4){if(!A){document.getElementById('pfETerms').style.display='block';ok=false;fe='pfTermsRow'}else document.getElementById('pfETerms').style.display='none'};if(fe){var f=document.getElementById(fe);if(f)f.scrollIntoView({block:'center',behavior:'smooth'})};return ok}
  function U(){for(let i=1;i<=4;i++){const c=document.getElementById('pfsc'+i),l=document.getElementById('pfsl-'+i);c.classList.remove('pf-active','pf-done');l.classList.remove('pf-active','pf-done');if(i<C){c.classList.add('pf-done');c.innerHTML='\u2713';l.classList.add('pf-done')}else if(i===C){c.classList.add('pf-active');c.innerHTML='0'+i;l.classList.add('pf-active')}else c.innerHTML='0'+i;if(i<4){const ln=document.getElementById('pfsl'+i);if(i<C)ln.classList.add('pf-done');else ln.classList.remove('pf-done')}};document.getElementById('pfCounter').textContent='STEP '+C+' OF 4';document.getElementById('pfBtnBack').style.display=C>1?'block':'none';document.getElementById('pfBtnNext').textContent=C===4?'SUBMIT PROJECT \u2713':'NEXT \u2192'}
  function R(){document.getElementById('pfRName').textContent=document.getElementById('pfName').value||'\u2014';document.getElementById('pfREmail').textContent=document.getElementById('pfEmail').value||'\u2014';document.getElementById('pfRPhone').textContent=document.getElementById('pfPhone').value||'Not provided';document.getElementById('pfRCompany').textContent=document.getElementById('pfCompany').value||'Not provided';document.getElementById('pfRCountry').textContent=document.getElementById('pfCountry').value||'\u2014';document.getElementById('pfRBudget').textContent=V[document.getElementById('pfBudgetSlider').value];document.getElementById('pfRTimeline').textContent=T;const d=document.getElementById('pfDesc').value;document.getElementById('pfRDesc').textContent=d.length>120?d.substring(0,120)+'...':d;const tc=document.getElementById('pfRSvcs');tc.innerHTML='';S.forEach(s=>{const t=document.createElement('span');t.className='pf-svc-tag';t.textContent=s;tc.appendChild(t)})}
  window.pfNext=function(){if(!Vd())return;if(C===4){Sd();return};document.getElementById('pfStep'+C).classList.remove('pf-step-active');C++;document.getElementById('pfStep'+C).classList.add('pf-step-active');if(C===4)R();U();document.getElementById('pfModal').scrollTop=0};
  window.pfPrev=function(){document.getElementById('pfStep'+C).classList.remove('pf-step-active');C--;document.getElementById('pfStep'+C).classList.add('pf-step-active');U();document.getElementById('pfModal').scrollTop=0};
  async function Sd(){const btn=document.getElementById('pfBtnNext');btn.textContent='SUBMITTING...';btn.disabled=true;const p={access_key:(typeof WEB3FORMS_KEY!=='undefined'?WEB3FORMS_KEY:'f5792651-e546-4e3e-a788-216ec76ab809'),subject:'New Project Inquiry \u2014 Xoos Digital',from_name:document.getElementById('pfName').value,email:document.getElementById('pfEmail').value,message:'NEW PROJECT INQUIRY\n====================\nName: '+document.getElementById('pfName').value+'\nEmail: '+document.getElementById('pfEmail').value+'\nPhone: '+(document.getElementById('pfPhone').value||'Not provided')+'\nCompany: '+(document.getElementById('pfCompany').value||'Not provided')+'\nCountry: '+document.getElementById('pfCountry').value+'\n\nSERVICES: '+S.join(', ')+'\nBUDGET: '+V[document.getElementById('pfBudgetSlider').value]+'\nTIMELINE: '+T+'\n\nDESCRIPTION:\n'+document.getElementById('pfDesc').value};try{const f=new URLSearchParams();f.append('name',document.getElementById('pfName').value);f.append('email',document.getElementById('pfEmail').value);f.append('phone',document.getElementById('pfPhone').value||'');f.append('company',document.getElementById('pfCompany').value||'');f.append('country',document.getElementById('pfCountry').value);f.append('services',S.join(', '));f.append('budget',V[document.getElementById('pfBudgetSlider').value]);f.append('timeline',T);f.append('message',document.getElementById('pfDesc').value);fetch('/contact-save.php',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:f}).catch(function(){});const r=await fetch('https://api.web3forms.com/submit',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(p)});const d=await r.json();if(d.success){document.getElementById('pfStep4').classList.remove('pf-step-active');document.getElementById('pfStep5').classList.add('pf-step-active');document.getElementById('pfRefCode').textContent='XD-'+Math.random().toString(36).substr(2,6).toUpperCase();document.getElementById('pfProgressWrap').style.display='none';document.getElementById('pfFooter').style.display='none';document.getElementById('pfModal').scrollTop=0}else{btn.textContent='TRY AGAIN \u2192';btn.disabled=false;alert('Something went wrong. Please try again.')}}catch(err){btn.textContent='TRY AGAIN \u2192';btn.disabled=false;alert('Network error. Please check your connection.')}}
  document.addEventListener('keydown',e=>{if(e.key==='Escape')closeProjectForm()});U();
})();